### PR TITLE
Example layouts for both Search and MP/MSP list pages

### PR DESCRIPTION
**Pull request by zarino**
The MP pages from #838 were so similar to the Search pages that I figured it'd be a quick job to repurpose the same layout. So here it is.

Take a look at http://twfy.mysociety/mps/new and http://twfy.mysociety/mps/new/with-postcode

I'm not 100% percent happy with the mess in the sidebar, but it's a good start for only one or two hours’ work.

Connects to #838

### CODE REVIEW

**Comment by wrightmartin** [comment]
Looking great!

You could give the sidebar survey similar styling to the secondary box at the bottom of the MP pages? 
screen shot 2015-05-20 at 17 21 11

Some other feedback - I think there's a lack of contrast in the MP list that's making it feel busy. Have you tried setting the constituency and party type in a lighter shade? You could probably get away with a touch more vertical whitespace between the results too

I can't tell if the sorting controls should come before or after the A-Z pagination, it might be right as it is, but I'm not 100% sure

**Comment by zarino** [comment]
Maybe we could clean up that sidebar by not using a `form`, and instead having something less obtrusive, like a link:

toggle

**Comment by zarino** [comment]
@struan: I'm happy with how this looks now, after the tweaks in https://github.com/mysociety/theyworkforyou/commit/4c8b0eee923dcc7d9effe089bb809b82217d45c2.

As ever, let me know if there are any unhandled edge-cases that need styling, once you've implemented it.

**Comment by struan** [comment]
Connects to #838

**Comment by struan** [comment]
Closing in favour of #932 due to merge awfulness with this.

**Pull request closed without merging**
