### PR TITLE
Improved day links accessibility for calendar component

### PR DESCRIPTION
**Pull request by lucascumsille**
Fixes: https://github.com/mysociety/theyworkforyou/issues/1833

https://github.com/user-attachments/assets/29b09377-c00a-4383-b489-85ed8a505e9e

Just in case the "Green one" is the active day

### CODE REVIEW

**Comment by ajparsons** [comment]
Good fix - but I think this specific blue looks like a "you have selected the following date range".

A lighter one maybe (example below, but that then has problems with the white text...)? Otherwise seems fine.

image

**Comment by lucascumsille** [comment]
@ajparsons  I was hoping the space would be enough to make obvious that is not a range, but it didn't work. Instead of going for adding background, I went for text-decoration + font-weight to make it pop up more. I think now they are quite noticeable a link. I added some off-set for the underline so the numbers are easier to read as well.

Let me know what you think.

**Comment by lucascumsille** [comment]
@ajparsons I updated the video at the top.

**Review by ajparsons — APPROVED** [review]
Ah, that's a great fix - loaded it up and looks fine!

Just need to squish the fixup commit when merging.

**Pull request merged**
