### PR TITLE
Vagrant adjustments

### PR DESCRIPTION
**Pull request by sagepe**
This updates the php7-xapian build script and uses a Vagrant box with Guest Additions installed rather than NFS.

Tested on a fresh clone (with submodules) - the box built successfully.

### CODE REVIEW

**Comment by dracos** [comment]
Does this still need including?

**Comment by sagepe** [comment]
> Does this still need including?

Seeing as we might be about to upgrade Xapian, probably worth waiting until that's done, they I'll review and either close or update and nudge you for a final review.

**Comment by ajparsons** [comment]
Given we don't use vagrant anymore and we haven't merged this so far - could we close or do we need to merge at some point?

**Comment by sagepe** [comment]
I'd say if we're not supporting Vagrant any more it can be closed, but I'd also suggest we remove the rest of the Vagrant stuff for cleanliness as well.

**Comment by ajparsons** [comment]
Closing as Vagrant support removed

**Pull request closed without merging**
