### PR TITLE
Ignore additional structural tags in regmem XML

### PR DESCRIPTION
**Pull request by andylolz**
This update will parse the regmem XML structure currently output by parlparse, as well as the modified structure proposed in mysociety/parlparse#10.

### CODE REVIEW

**Comment by dracos** [comment]
I would be happy for this to actually do something with the new structure! :) Put them in a wrapper div, that can then be styled?

**Comment by andylolz** [comment]
Hi Matthew! I have a question about this one (sorry!) Do you think you’l retrospectively update the old XML that drives TheyWorkForYou, so it all has the new structure? (That would be awesome.) If so, it probably makes adding divs here a bit easier.

**Comment by dracos** [comment]
Hmm, it seems doubtful anyone is relying on them, so I don't see why not. They can always regenerate them old style if need be anyway.

**Comment by struan** [comment]
Closed in a925b88f14e106395cc90cdcf53996d30c59bf2a

**Pull request closed without merging**
