### PR TITLE
Homepage improvements

### PR DESCRIPTION
**Pull request by lucascumsille**
### Fixes:
The first commit should improve the overlapping of the searchbar on the next element.
I also added some other commits to fix the following:

**Spacing problems in the homepage(mobile)**
Screenshot 2024-09-12 at 14 39 56

**Odd border radius on mobile**
Screenshot 2024-09-12 at 14 40 47
Screenshot 2024-09-12 at 14 41 00

**Horizontal spacing on mobile not consistent with the rest of the page**
Screenshot 2024-09-12 at 14 47 28

### Preview
https://github.com/user-attachments/assets/fc79baf9-f632-4923-ba29-7532a02bf6e8

### CODE REVIEW

**Comment by ajparsons** [comment]
I think this is all good opening on the test server. I *think* this can be merged but was possibly draft because I said I wanted to roll some other stuff in Monday.

**Comment by lucascumsille** [comment]
@ajparsons Yes that's why I left it as a draft.

**Comment by ajparsons** [comment]
Okay, I'm taking too long. let's convert this to a real PR monday  but I loaded it and can approve

**Comment by lucascumsille** [comment]
Thanks @ajparsons I just made it a PR =)

**Pull request merged**
